id: I213E41A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:43:43+00:00'
last_modified: '2022-06-07T16:35:55.219010+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27938
  title: ལས་སྒྲིབ་རྒྱུན་གཅོད་ཀྱི་སྔགས་བརྒྱ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    361B:
      image_group_id: I4530
      title: ''
      total_pages: 154
      order: 1
      base_file: 361B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
