id: I213E41A5
legacy_id: P002962
ocr_import_info:
  bdrc_scan_id: W27938
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:42:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:14:54.478894+00:00'
last_modified: 2022-09-02 16:15:17.586196
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27938
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27938
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལས་སྒྲིབ་རྒྱུན་གཅོད་ཀྱི་སྔགས་བརྒྱ་པ།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5836244918014419
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I4530:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4530
      total_pages: 154
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4530.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5836244918014419
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
